In [21]:
import pandas as pd
import numpy as np
import warnings

warnings.filterwarnings("ignore")
pd.set_option('display.max_columns', None)

In [22]:
original = pd.read_csv(r'..\..\datasets\nfs_cleaned_most_common_ncm.csv', encoding='latin-1')

iforest = pd.read_csv(r'..\iforest\output\outliers.csv', encoding='latin-1')
iforest = iforest['idx']

som = pd.read_csv(r'..\som\output\outliers.csv', encoding='latin-1')
som = som['idx']

lof = pd.read_csv(r'..\lof\output\outliers.csv', encoding='latin-1')
lof = lof['idx']

intersec1 = pd.read_csv(r'output\som_iforest_intersec.csv', encoding='latin-1')
intersec1 = intersec1['idx']

intersec2 = pd.read_csv(r'output\som_lof_intersec.csv', encoding='latin-1')
intersec2 = intersec2['idx']

intersec3 = pd.read_csv(r'output\lof_iforest_intersec.csv', encoding='latin-1')
intersec3 = intersec3['idx']

intersec4 = pd.read_csv(r'output\all_intersec.csv', encoding='latin-1')
intersec4 = intersec4['idx']

In [23]:
iforest_rows = original.loc[iforest]
iforest_rows['idx'] = iforest_rows.index
iforest_rows.to_csv(r'output\iforest_real_values.csv', encoding='utf-8', index=False)
iforest_rows.info()

,nf_numero,nf_item,nf_timestamp,nf_valor_total,emit_cnpj,emit_cep,emit_lat,emit_long,prod_ncm,prod_cfop,prod_quant,prod_valor_unit,prod_valor_total,idx
count,7.640000e+02,764.000000,7.640000e+02,764.000000,7.640000e+02,7.640000e+02,764.000000,764.000000,764.0,764.000000,764.000000,764.000000,764.000000,764.00000
mean,1.225232e+05,9.261780,1.470008e+09,22445.832526,1.814615e+13,4.913514e+07,-21.252305,-49.778167,30049099.0,5576.073298,6409.594241,74.869332,8021.833272,66450.59555
std,2.350562e+05,17.222225,9.472503e+06,54359.809342,1.896589e+13,1.981348e+07,6.339533,5.394442,0.0,1170.626982,17987.704534,272.321073,26058.411430,7924.43574
min,1.400000e+01,1.000000,1.451892e+09,1.100000,1.131601e+12,5.856800e+06,-31.287471,-63.852061,30049099.0,1411.000000,1.000000,0.040000,0.400000,40617.00000
25%,1.010000e+02,1.000000,1.460124e+09,2583.125000,9.020529e+12,3.303002e+07,-23.706625,-52.428591,30049099.0,5403.000000,15.000000,0.160000,154.010000,62274.75000
50%,5.240350e+04,3.000000,1.471464e+09,6145.590000,1.189654e+13,5.815500e+07,-21.790032,-49.253269,30049099.0,6107.000000,1060.000000,2.000000,737.200000,70821.50000
75%,1.755200e+05,11.000000,1.478681e+09,17928.000000,1.344464e+13,5.882400e+07,-16.680882,-46.564793,30049099.0,6108.000000,3400.000000,17.270000,3945.000000,72294.25000
max,1.640228e+06,184.000000,1.483097e+09,401994.600000,7.385659e+13,9.974000e+07,2.820848,-38.521799,30049099.0,6949.000000,200000.000000,1665.640000,375467.400000,76456.00000

In [24]:
som_rows = original.loc[som]
som_rows['idx'] = som_rows.index
som_rows.to_csv(r'output\som_real_values.csv', encoding='utf-8', index=False)
som_rows.info()

,nf_numero,nf_item,nf_timestamp,nf_valor_total,emit_cnpj,emit_cep,emit_lat,emit_long,prod_ncm,prod_cfop,prod_quant,prod_valor_unit,prod_valor_total,idx
count,7.650000e+02,765.000000,7.650000e+02,765.000000,7.650000e+02,7.650000e+02,765.000000,765.000000,765.0,765.000000,765.000000,765.000000,765.000000,765.000000
mean,1.366799e+05,12.603922,1.468368e+09,26549.507908,1.722082e+13,5.175148e+07,-17.355314,-46.098386,30049099.0,5774.320261,5735.775150,208.012641,12077.955582,60960.975163
std,3.015505e+05,33.049602,8.871317e+06,63867.871054,1.984078e+13,1.856097e+07,8.120313,6.097318,0.0,867.711061,28275.389466,1035.688505,49519.399463,12817.212026
min,1.000000e+00,1.000000,1.452018e+09,0.000000,8.582200e+10,3.185010e+06,-31.287471,-63.852061,30049099.0,2201.000000,1.000000,0.000000,0.000000,764.000000
25%,6.600000e+01,1.000000,1.460127e+09,3129.500000,4.238989e+12,3.764000e+07,-22.911014,-51.089799,30049099.0,5403.000000,4.000000,2.200000,147.000000,50881.000000
50%,2.702900e+04,3.000000,1.467981e+09,7480.000000,9.053134e+12,5.838000e+07,-19.968056,-46.527770,30049099.0,6102.000000,48.000000,11.600000,760.000000,63839.000000
75%,1.012960e+05,12.000000,1.476775e+09,19965.000000,1.522444e+13,5.897000e+07,-10.333333,-43.209373,30049099.0,6108.000000,550.000000,53.000000,3975.000000,71785.000000
max,1.638001e+06,399.000000,1.483116e+09,543120.000000,7.385659e+13,9.974000e+07,2.820848,-34.835161,30049099.0,6949.000000,300000.000000,11661.170000,616920.000000,76456.000000

In [25]:
lof_rows = original.loc[lof]
lof_rows['idx'] = lof_rows.index
lof_rows.to_csv(r'output\lof_real_values.csv', encoding='utf-8', index=False)
lof_rows.info()

,nf_numero,nf_item,nf_timestamp,nf_valor_total,emit_cnpj,emit_cep,emit_lat,emit_long,prod_ncm,prod_cfop,prod_quant,prod_valor_unit,prod_valor_total,idx
count,7.650000e+02,765.000000,7.650000e+02,765.000000,7.650000e+02,7.650000e+02,765.000000,765.000000,765.0,765.000000,765.000000,765.000000,765.000000,765.000000
mean,3.557359e+04,74.462745,1.465825e+09,22286.012654,9.385377e+12,5.826415e+07,-8.432869,-38.707319,30049099.0,5706.226144,2856.175163,205.830392,7032.136889,50411.014379
std,1.401456e+05,127.182498,1.061105e+07,50780.613208,1.060963e+13,8.900822e+06,4.527672,6.123428,0.0,544.109114,22002.982168,948.375870,45601.962619,16962.710174
min,1.000000e+00,1.000000,1.452007e+09,0.000000,5.101850e+11,5.838800e+06,-27.635071,-63.852061,30049099.0,1202.000000,1.000000,0.000000,0.000000,221.000000
25%,1.790000e+02,4.000000,1.456272e+09,3015.970000,1.571702e+12,5.804000e+07,-7.487004,-38.172722,30049099.0,5403.000000,1.000000,10.570000,46.320000,36383.000000
50%,5.870000e+02,19.000000,1.464048e+09,7485.590000,7.322518e+12,5.834000e+07,-7.121598,-35.877129,30049099.0,5929.000000,1.000000,44.130000,101.200000,49378.000000
75%,4.264000e+03,77.000000,1.476894e+09,24579.320000,1.083170e+13,5.875500e+07,-7.025829,-34.882028,30049099.0,5929.000000,10.000000,96.200000,298.800000,66695.000000
max,1.638001e+06,618.000000,1.483214e+09,543120.000000,7.010434e+13,9.974000e+07,-1.450560,-34.835161,30049099.0,6949.000000,300000.000000,8514.000000,616920.000000,76453.000000

In [26]:
intersec1 = original.loc[intersec1]
intersec1['idx'] = intersec1.index
intersec1.to_csv(r'output\som_iforest_real_values.csv', encoding='utf-8', index=False)
intersec1.info()

,nf_numero,nf_item,nf_timestamp,nf_valor_total,emit_cnpj,emit_cep,emit_lat,emit_long,prod_ncm,prod_cfop,prod_quant,prod_valor_unit,prod_valor_total,idx
count,2.180000e+02,218.000000,2.180000e+02,218.000000,2.180000e+02,2.180000e+02,218.000000,218.000000,218.0,218.000000,218.000000,218.000000,218.000000,218.000000
mean,1.125603e+05,6.600917,1.468174e+09,36044.586881,1.900995e+13,4.775067e+07,-24.285715,-49.330959,30049099.0,5809.082569,11044.252294,85.576743,14319.596284,64335.284404
std,2.507210e+05,9.625781,9.350921e+06,73022.859693,1.906160e+13,2.199957e+07,5.309506,4.269711,0.0,820.085430,29918.532637,240.375056,42863.812307,8529.529886
min,1.400000e+01,1.000000,1.452257e+09,60.000000,1.131601e+12,5.856800e+06,-31.287471,-63.852061,30049099.0,2202.000000,1.000000,0.040000,1.500000,46587.000000
25%,2.600000e+01,1.000000,1.459123e+09,4405.592500,8.706710e+12,3.303002e+07,-28.827247,-52.510916,30049099.0,5403.000000,9.250000,1.360000,508.282500,62245.750000
50%,3.615600e+04,2.000000,1.467585e+09,9532.715000,1.189654e+13,5.815500e+07,-23.489406,-49.489593,30049099.0,6015.500000,710.000000,6.210000,2738.140000,65066.500000
75%,6.660200e+04,8.000000,1.476762e+09,29336.000000,3.378106e+13,5.882400e+07,-21.790032,-46.527770,30049099.0,6108.000000,5000.000000,43.500000,7397.500000,71798.250000
max,1.638001e+06,58.000000,1.483097e+09,401994.600000,7.385659e+13,9.974000e+07,2.820848,-38.521799,30049099.0,6949.000000,200000.000000,1665.640000,375467.400000,76456.000000

In [27]:
intersec2 = original.loc[intersec2]
intersec2['idx'] = intersec2.index
intersec2.to_csv(r'output\som_lof_real_values.csv', encoding='utf-8', index=False)
intersec2.info()

,nf_numero,nf_item,nf_timestamp,nf_valor_total,emit_cnpj,emit_cep,emit_lat,emit_long,prod_ncm,prod_cfop,prod_quant,prod_valor_unit,prod_valor_total,idx
count,1.030000e+02,103.000000,1.030000e+02,103.000000,1.030000e+02,1.030000e+02,103.000000,103.000000,103.0,103.000000,103.000000,103.000000,103.000000,103.000000
mean,1.201178e+05,18.184466,1.469279e+09,63963.391068,1.282700e+13,5.564777e+07,-13.291774,-45.642727,30049099.0,5784.796117,18286.048544,811.089126,48943.056311,56058.320388
std,3.364614e+05,48.826172,9.587813e+06,113572.328447,1.340594e+13,1.973635e+07,8.202070,7.388764,0.0,648.898015,57473.927136,2231.924268,116241.319056,18536.628681
min,1.000000e+00,1.000000,1.452018e+09,0.000000,9.585480e+11,5.856800e+06,-27.635071,-63.852061,30049099.0,2201.000000,1.000000,0.000000,0.000000,7316.000000
25%,1.140000e+02,1.000000,1.460234e+09,3420.240000,5.008240e+12,5.823300e+07,-22.436111,-52.497605,30049099.0,5403.000000,2.000000,2.495000,183.750000,46399.500000
50%,4.039000e+03,3.000000,1.469098e+09,9997.360000,8.307548e+12,5.873500e+07,-10.980708,-46.821667,30049099.0,5929.000000,24.000000,20.000000,1080.000000,62178.000000
75%,8.422650e+04,18.000000,1.478304e+09,75547.500000,1.371972e+13,5.960724e+07,-7.224674,-38.521799,30049099.0,6108.000000,1402.500000,140.935000,37520.520000,72557.500000
max,1.638001e+06,399.000000,1.482924e+09,543120.000000,5.699450e+13,9.974000e+07,-1.561870,-34.884819,30049099.0,6949.000000,300000.000000,8514.000000,616920.000000,76453.000000

In [28]:
intersec3 = original.loc[intersec3]
intersec3['idx'] = intersec3.index
intersec3.to_csv(r'output\lof_iforest_real_values.csv', encoding='utf-8', index=False)
intersec3.info()

,nf_numero,nf_item,nf_timestamp,nf_valor_total,emit_cnpj,emit_cep,emit_lat,emit_long,prod_ncm,prod_cfop,prod_quant,prod_valor_unit,prod_valor_total,idx
count,3.800000e+01,38.000000,3.800000e+01,38.000000,3.800000e+01,3.800000e+01,38.000000,38.000000,38.0,38.000000,38.000000,38.000000,38.000000,38.000000
mean,2.913324e+05,7.342105,1.472269e+09,58460.418158,1.117103e+13,6.485733e+07,-18.717372,-51.276126,30049099.0,5909.947368,17012.763158,101.885526,23044.539737,69443.105263
std,4.206437e+05,11.423722,1.015673e+07,92775.305695,1.735515e+13,2.779055e+07,6.124197,5.456983,0.0,718.220923,44186.165615,318.787858,61385.312380,6056.311610
min,1.120000e+02,1.000000,1.452278e+09,794.940000,1.422330e+12,5.856800e+06,-27.635071,-63.852061,30049099.0,2202.000000,1.000000,0.050000,1.500000,46601.000000
25%,5.939850e+04,1.000000,1.465919e+09,4108.750000,1.571702e+12,5.838000e+07,-22.792288,-52.376532,30049099.0,6107.000000,850.000000,0.860000,1305.000000,66042.750000
50%,2.341200e+05,1.000000,1.476817e+09,10912.500000,2.520829e+12,7.477503e+07,-16.680882,-49.253269,30049099.0,6107.000000,1500.000000,2.000000,3972.500000,72106.500000
75%,2.454045e+05,6.500000,1.480995e+09,50194.100000,9.020529e+12,7.477503e+07,-16.680882,-49.253269,30049099.0,6108.000000,2475.000000,5.800000,11025.000000,72236.000000
max,1.638001e+06,42.000000,1.482924e+09,313785.900000,6.772918e+13,9.974000e+07,-8.033317,-43.209373,30049099.0,6923.000000,200000.000000,1576.710000,356574.890000,76343.000000

In [29]:
intersec4 = original.loc[intersec4]
intersec4['idx'] = intersec4.index
intersec4.to_csv(r'output\all_intersec_real_values.csv', encoding='utf-8', index=False)
intersec4.info()

,nf_numero,nf_item,nf_timestamp,nf_valor_total,emit_cnpj,emit_cep,emit_lat,emit_long,prod_ncm,prod_cfop,prod_quant,prod_valor_unit,prod_valor_total,idx
count,1.500000e+01,15.000000,1.500000e+01,15.000000,1.500000e+01,1.500000e+01,15.000000,15.000000,15.0,15.000000,15.000000,15.000000,15.000000,15.000000
mean,4.285400e+05,8.733333,1.469935e+09,98073.188667,1.886783e+13,5.335070e+07,-22.769822,-49.984510,30049099.0,6055.666667,37332.000000,209.344667,51842.834000,67569.733333
std,6.318274e+05,11.865115,1.058381e+07,101241.129520,1.982454e+13,3.939219e+07,5.239098,5.031833,0.0,484.815085,65484.224043,465.575353,92047.583947,8702.079895
min,1.120000e+02,1.000000,1.456159e+09,794.940000,1.422330e+12,5.856800e+06,-27.635071,-63.852061,30049099.0,5102.000000,1.000000,0.050000,1.500000,46601.000000
25%,1.072450e+04,1.000000,1.460561e+09,13893.395000,2.520829e+12,1.397490e+07,-27.621469,-52.376532,30049099.0,6107.500000,178.500000,0.280000,982.500000,64507.500000
50%,1.178260e+05,1.000000,1.466520e+09,50258.800000,9.020529e+12,5.823300e+07,-22.911014,-49.245255,30049099.0,6108.000000,1000.000000,1.930000,18000.000000,71968.000000
75%,5.473995e+05,17.500000,1.480991e+09,173515.800000,3.899121e+13,9.972000e+07,-21.786845,-46.821667,30049099.0,6108.000000,40000.000000,95.795000,50129.400000,72998.000000
max,1.638001e+06,38.000000,1.482924e+09,313785.900000,5.699450e+13,9.974000e+07,-8.033317,-43.209373,30049099.0,6923.000000,200000.000000,1576.710000,356574.890000,76343.000000

In [30]:
query = original[original['prod_desc'].str.contains('simeticona', case=False) & (original['prod_unid'] == 'cp')]
query

,nf_numero,nf_item,nf_datahora,nf_timestamp,nf_valor_total,emit_nome,emit_cnpj,emit_bairro,emit_municipio,emit_cep,emit_lat,emit_long,prod_desc,prod_ncm,prod_cfop,prod_quant,prod_unid,prod_valor_unit,prod_valor_total
11150,857,11,2016-03-17 16:17:17,1458231437,27249.41,mm comercial de medicamentos ltda me,13312369000181,sao jose,campina grande,58400370,-7.224674,-35.877129,dimeticona 40mg (simeticona) (g) cx c/600,30049099,5904,600.0,cp,0.18,108.0
17878,15747,3,2016-11-22 17:25:55,1479835555,4714.50,medfarmacy hospitalar ltda,10806118000165,velame,campina grande,58420450,-7.224674,-35.877129,simeticona 40mg comprimidos,30049099,5403,600.0,cp,0.09,54.0
39530,3402,19,2016-01-06 00:00:00,1452038400,2304.96,distribuidora salutte ltda - me,9193047000193,centro,guarabira,58200000,-6.851398,-35.491558,simeticona 40mg,30049099,5102,600.0,cp,0.08,48.0
47885,3412,42,2016-02-05 00:00:00,1454630400,9546.77,dismene distr. de medicamentos do nordeste ltda,16682179000144,centro,timbauba,55870000,-7.511882,-35.316076,simeticona 40mg c/600 comp-(imposto ibpt nacio...,30049099,6403,500.0,cp,0.08,40.0
48046,3560,92,2016-03-12 00:00:00,1457740800,11892.35,dismene distr. de medicamentos do nordeste ltda,16682179000144,centro,timbauba,55870000,-7.511882,-35.316076,simeticona 40mg c/600 comp-(imposto ibpt nacio...,30049099,6403,500.0,cp,0.08,40.0
48068,3911,10,2016-05-25 00:00:00,1464134400,4983.98,dismene distr. de medicamentos do nordeste ltda,16682179000144,centro,timbauba,55870000,-7.511882,-35.316076,simeticona 40mg c/600 comp-(imposto ibpt nacio...,30049099,6403,600.0,cp,0.13,78.0
48076,3911,33,2016-05-25 00:00:00,1464134400,4983.98,dismene distr. de medicamentos do nordeste ltda,16682179000144,centro,timbauba,55870000,-7.511882,-35.316076,simeticona 40mg c/600 comp-(imposto ibpt nacio...,30049099,6403,1000.0,cp,0.13,130.0
48185,156,92,2016-03-14 00:00:00,1457913600,11892.35,dismene distr. de medicamentos do nordeste ltda,16682179000144,centro,timbauba,55870000,-7.511882,-35.316076,simeticona 40mg c/600 comp-(imposto ibpt nacio...,30049099,2411,500.0,cp,0.08,40.0
48408,154,42,2016-02-11 00:00:00,1455148800,9546.77,dismene distr. de medicamentos do nordeste ltda,16682179000144,centro,timbauba,55870000,-7.511882,-35.316076,simeticona 40mg c/600 comp-(imposto ibpt nacio...,30049099,2411,500.0,cp,0.08,40.0
48838,3881,45,2016-05-19 00:00:00,1463616000,17114.46,dismene distr. de medicamentos do nordeste ltda,16682179000144,centro,timbauba,55870000,-7.511882,-35.316076,simeticona 40mg c/600 comp-(imposto ibpt nacio...,30049099,6403,1120.0,cp,0.13,145.6
48981,3724,8,2016-04-15 00:00:00,1460678400,3540.60,dismene distr. de medicamentos do nordeste ltda,16682179000144,centro,timbauba,55870000,-7.511882,-35.316076,simeticona 40mg c/600 comp-(imposto ibpt nacio...,30049099,6403,500.0,cp,0.13,65.0
76294,443067,2,2016-08-29 18:13:48,1472494428,60.00,"prati,donaduzzi e cia ltda",73856593000166,c ind nilton arruda,toledo,85903630,-22.743397,-46.373504,- simeticona 40mg 30x20 cps-vp / gen dimeticona,30049099,6107,600.0,cp,0.07,42.0
76295,443070,3,2016-08-29 18:14:16,1472494456,228.00,"prati,donaduzzi e cia ltda",73856593000166,c ind nilton arruda,toledo,85903630,-22.743397,-46.373504,- simeticona 40mg 30x20 cps-vp / gen dimeticona,30049099,6107,1800.0,cp,0.07,126.0
76296,443325,3,2016-08-30 15:55:25,1472572525,766.00,"prati,donaduzzi e cia ltda",73856593000166,c ind nilton arruda,toledo,85903630,-22.743397,-46.373504,- simeticona 40mg 30x20 cps-vp / gen dimeticona,30049099,6107,1800.0,cp,0.07,126.0
76297,443326,3,2016-08-30 15:55:45,1472572545,766.00,"prati,donaduzzi e cia ltda",73856593000166,c ind nilton arruda,toledo,85903630,-22.743397,-46.373504,- simeticona 40mg 30x20 cps-vp / gen dimeticona,30049099,6107,1800.0,cp,0.07,126.0
76298,443023,1,2016-08-29 17:26:54,1472491614,1722.00,"prati,donaduzzi e cia ltda",73856593000166,c ind nilton arruda,toledo,85903630,-22.743397,-46.373504,- simeticona 40mg 30x20 cps-vp / gen dimeticona,30049099,6107,24600.0,cp,0.07,1722.0
76299,443024,3,2016-08-29 17:27:08,1472491628,190.00,"prati,donaduzzi e cia ltda",73856593000166,c ind nilton arruda,toledo,85903630,-22.743397,-46.373504,- simeticona 40mg 30x20 cps-vp / gen dimeticona,30049099,6107,1800.0,cp,0.07,126.0
76300,443025,1,2016-08-29 17:27:21,1472491641,336.00,"prati,donaduzzi e cia ltda",73856593000166,c ind nilton arruda,toledo,85903630,-22.743397,-46.373504,- simeticona 40mg 30x20 cps-vp / gen dimeticona,30049099,6107,4800.0,cp,0.07,336.0