In [16]:
import pandas as pd
import numpy as np
import warnings

warnings.filterwarnings("ignore")
pd.set_option('display.max_columns', None)

In [17]:
original = pd.read_csv(r'..\..\datasets\nfs_cleaned_most_common_ncm.csv', encoding='latin-1')

iforest = pd.read_csv(r'..\iforest\output\outliers.csv', encoding='latin-1')
iforest = iforest['idx']

som = pd.read_csv(r'..\som\output\outliers.csv', encoding='latin-1')
som = som['idx']

lof = pd.read_csv(r'..\lof\output\outliers.csv', encoding='latin-1')
lof = lof['idx']

intersec1 = pd.read_csv(r'output\som_iforest_intersec.csv', encoding='latin-1')
intersec1 = intersec1['idx']

intersec2 = pd.read_csv(r'output\som_lof_intersec.csv', encoding='latin-1')
intersec2 = intersec2['idx']

intersec3 = pd.read_csv(r'output\lof_iforest_intersec.csv', encoding='latin-1')
intersec3 = intersec3['idx']

intersec4 = pd.read_csv(r'output\all_intersec.csv', encoding='latin-1')
intersec4 = intersec4['idx']

In [18]:
iforest_rows = original.loc[iforest]
iforest_rows['idx'] = iforest_rows.index
iforest_rows.to_csv(r'output\iforest_real_values.csv', encoding='utf-8', index=False)
iforest_rows.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 764 entries, 71964 to 55970
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   nf_numero         764 non-null    int64
 1   nf_item           764 non-null    int64
 2   nf_datahora       764 non-null    object
 3   nf_timestamp      764 non-null    int64
 4   nf_valor_total    764 non-null    float64
 5   emit_nome         764 non-null    object
 6   emit_cnpj         764 non-null    int64
 7   emit_bairro       764 non-null    object
 8   emit_municipio    764 non-null    object
 9   emit_cep          764 non-null    int64
 10  emit_lat          764 non-null    float64
 11  emit_long         764 non-null    float64
 12  prod_desc         764 non-null    object
 13  prod_ncm          764 non-null    int64
 14  prod_cfop         764 non-null    int64
 15  prod_quant        764 non-null    float64
 16  prod_unid         764 non-null    object
 17  prod_valor_unit   764 non-null    float64
 18  prod_valor_total  764 non-null    float64
 19  idx               764 non-null    int64
dtypes: float64(6), int64(8), object(6)
memory usage: 125.3+ KB

In [19]:
som_rows = original.loc[som]
som_rows['idx'] = som_rows.index
som_rows.to_csv(r'output\som_real_values.csv', encoding='utf-8', index=False)
som_rows.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 765 entries, 70971 to 55230
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   nf_numero         765 non-null    int64
 1   nf_item           765 non-null    int64
 2   nf_datahora       765 non-null    object
 3   nf_timestamp      765 non-null    int64
 4   nf_valor_total    765 non-null    float64
 5   emit_nome         765 non-null    object
 6   emit_cnpj         765 non-null    int64
 7   emit_bairro       765 non-null    object
 8   emit_municipio    765 non-null    object
 9   emit_cep          765 non-null    int64
 10  emit_lat          765 non-null    float64
 11  emit_long         765 non-null    float64
 12  prod_desc         765 non-null    object
 13  prod_ncm          765 non-null    int64
 14  prod_cfop         765 non-null    int64
 15  prod_quant        765 non-null    float64
 16  prod_unid         765 non-null    object
 17  prod_valor_unit   765 non-null    float64
 18  prod_valor_total  765 non-null    float64
 19  idx               765 non-null    int64
dtypes: float64(6), int64(8), object(6)
memory usage: 125.5+ KB

In [20]:
lof_rows = original.loc[lof]
lof_rows['idx'] = lof_rows.index
lof_rows.to_csv(r'output\lof_real_values.csv', encoding='utf-8', index=False)
lof_rows.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 765 entries, 72126 to 40329
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   nf_numero         765 non-null    int64
 1   nf_item           765 non-null    int64
 2   nf_datahora       765 non-null    object
 3   nf_timestamp      765 non-null    int64
 4   nf_valor_total    765 non-null    float64
 5   emit_nome         765 non-null    object
 6   emit_cnpj         765 non-null    int64
 7   emit_bairro       765 non-null    object
 8   emit_municipio    765 non-null    object
 9   emit_cep          765 non-null    int64
 10  emit_lat          765 non-null    float64
 11  emit_long         765 non-null    float64
 12  prod_desc         765 non-null    object
 13  prod_ncm          765 non-null    int64
 14  prod_cfop         765 non-null    int64
 15  prod_quant        765 non-null    float64
 16  prod_unid         765 non-null    object
 17  prod_valor_unit   765 non-null    float64
 18  prod_valor_total  765 non-null    float64
 19  idx               765 non-null    int64
dtypes: float64(6), int64(8), object(6)
memory usage: 125.5+ KB

In [21]:
intersec1 = original.loc[intersec1]
intersec1['idx'] = intersec1.index
intersec1.to_csv(r'output\som_iforest_real_values.csv', encoding='utf-8', index=False)
intersec1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 218 entries, 46592 to 46591
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   nf_numero         218 non-null    int64
 1   nf_item           218 non-null    int64
 2   nf_datahora       218 non-null    object
 3   nf_timestamp      218 non-null    int64
 4   nf_valor_total    218 non-null    float64
 5   emit_nome         218 non-null    object
 6   emit_cnpj         218 non-null    int64
 7   emit_bairro       218 non-null    object
 8   emit_municipio    218 non-null    object
 9   emit_cep          218 non-null    int64
 10  emit_lat          218 non-null    float64
 11  emit_long         218 non-null    float64
 12  prod_desc         218 non-null    object
 13  prod_ncm          218 non-null    int64
 14  prod_cfop         218 non-null    int64
 15  prod_quant        218 non-null    float64
 16  prod_unid         218 non-null    object
 17  prod_valor_unit   218 non-null    float64
 18  prod_valor_total  218 non-null    float64
 19  idx               218 non-null    int64
dtypes: float64(6), int64(8), object(6)
memory usage: 35.8+ KB

In [22]:
intersec2 = original.loc[intersec2]
intersec2['idx'] = intersec2.index
intersec2.to_csv(r'output\som_lof_real_values.csv', encoding='utf-8', index=False)
intersec2.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 49 entries, 72320 to 74235
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   nf_numero         49 non-null     int64
 1   nf_item           49 non-null     int64
 2   nf_datahora       49 non-null     object
 3   nf_timestamp      49 non-null     int64
 4   nf_valor_total    49 non-null     float64
 5   emit_nome         49 non-null     object
 6   emit_cnpj         49 non-null     int64
 7   emit_bairro       49 non-null     object
 8   emit_municipio    49 non-null     object
 9   emit_cep          49 non-null     int64
 10  emit_lat          49 non-null     float64
 11  emit_long         49 non-null     float64
 12  prod_desc         49 non-null     object
 13  prod_ncm          49 non-null     int64
 14  prod_cfop         49 non-null     int64
 15  prod_quant        49 non-null     float64
 16  prod_unid         49 non-null     object
 17  prod_valor_unit   49 non-null     float64
 18  prod_valor_total  49 non-null     float64
 19  idx               49 non-null     int64
dtypes: float64(6), int64(8), object(6)
memory usage: 8.0+ KB

In [23]:
intersec3 = original.loc[intersec3]
intersec3['idx'] = intersec3.index
intersec3.to_csv(r'output\lof_iforest_real_values.csv', encoding='utf-8', index=False)
intersec3.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 33 entries, 72194 to 72191
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   nf_numero         33 non-null     int64
 1   nf_item           33 non-null     int64
 2   nf_datahora       33 non-null     object
 3   nf_timestamp      33 non-null     int64
 4   nf_valor_total    33 non-null     float64
 5   emit_nome         33 non-null     object
 6   emit_cnpj         33 non-null     int64
 7   emit_bairro       33 non-null     object
 8   emit_municipio    33 non-null     object
 9   emit_cep          33 non-null     int64
 10  emit_lat          33 non-null     float64
 11  emit_long         33 non-null     float64
 12  prod_desc         33 non-null     object
 13  prod_ncm          33 non-null     int64
 14  prod_cfop         33 non-null     int64
 15  prod_quant        33 non-null     float64
 16  prod_unid         33 non-null     object
 17  prod_valor_unit   33 non-null     float64
 18  prod_valor_total  33 non-null     float64
 19  idx               33 non-null     int64
dtypes: float64(6), int64(8), object(6)
memory usage: 5.4+ KB

In [24]:
intersec4 = original.loc[intersec4]
intersec4['idx'] = intersec4.index
intersec4.to_csv(r'output\all_intersec_real_values.csv', encoding='utf-8', index=False)
intersec4.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 8 entries, 62178 to 70971
Data columns (total 20 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   nf_numero         8 non-null      int64
 1   nf_item           8 non-null      int64
 2   nf_datahora       8 non-null      object
 3   nf_timestamp      8 non-null      int64
 4   nf_valor_total    8 non-null      float64
 5   emit_nome         8 non-null      object
 6   emit_cnpj         8 non-null      int64
 7   emit_bairro       8 non-null      object
 8   emit_municipio    8 non-null      object
 9   emit_cep          8 non-null      int64
 10  emit_lat          8 non-null      float64
 11  emit_long         8 non-null      float64
 12  prod_desc         8 non-null      object
 13  prod_ncm          8 non-null      int64
 14  prod_cfop         8 non-null      int64
 15  prod_quant        8 non-null      float64
 16  prod_unid         8 non-null      object
 17  prod_valor_unit   8 non-null      float64
 18  prod_valor_total  8 non-null      float64
 19  idx               8 non-null      int64
dtypes: float64(6), int64(8), object(6)
memory usage: 1.3+ KB

In [134]:
query = original[original['prod_desc'].str.contains('alendronato de s', case=False) & original['prod_desc'].str.contains('70', case=False) & ((original['prod_unid'] == 'cpr') | (original['prod_unid'] == 'cp'))]
#query = original[original['prod_desc'].str.contains('norestin', case=False) & original['prod_desc'].str.contains('35', case=False) & (original['prod_unid'] == 'und')]
#query = original[original['prod_desc'].str.contains('fluconazol', case=False) & ((original['prod_unid'] == 'cpr') | (original['prod_unid'] == 'cp'))]
#query = original[original['prod_desc'].str.contains('diosmina', case=False) & (original['prod_unid'] == 'cp')]
#query = original[original['prod_desc'].str.contains('anestesico topico', case=False)]
query.describe()

,nf_numero,nf_item,nf_timestamp,nf_valor_total,emit_cnpj,emit_cep,emit_lat,emit_long,prod_ncm,prod_cfop,prod_quant,prod_valor_unit,prod_valor_total
count,24.000000,24.000000,2.400000e+01,24.000000,2.400000e+01,2.400000e+01,24.000000,24.000000,24.0,24.000000,24.000000,24.000000,24.000000
mean,21018.583333,3.666667,1.467377e+09,15811.825417,1.136776e+13,6.115530e+07,-9.023849,-37.096433,30049099.0,5699.458333,5814.583333,1.123750,2124.192500
std,30756.442898,3.655451,8.102371e+06,37943.413407,3.628453e+12,1.195012e+07,5.732007,4.714543,0.0,436.476702,24359.225179,0.523091,7486.412299
min,1990.000000,1.000000,1.452862e+09,2028.000000,2.520829e+12,5.431034e+07,-27.621469,-52.376532,30049099.0,5403.000000,200.000000,0.310000,165.000000
25%,11917.000000,1.750000,1.462105e+09,4473.125000,1.080612e+13,5.777326e+07,-7.511882,-35.877129,30049099.0,5403.000000,279.000000,0.550000,315.300000
50%,15013.000000,2.500000,1.466027e+09,7764.305000,1.080612e+13,5.840768e+07,-7.224674,-35.877129,30049099.0,5403.000000,400.000000,1.190000,573.500000
75%,15488.000000,4.000000,1.473353e+09,9909.850000,1.097354e+13,5.842045e+07,-7.224674,-35.736866,30049099.0,6108.000000,525.000000,1.670000,712.000000
max,127237.000000,17.000000,1.481104e+09,192380.000000,1.668218e+13,9.974000e+07,-7.224674,-34.946872,30049099.0,6403.000000,120000.000000,1.780000,37200.000000

In [135]:
pd.set_option('display.max_rows', None)
pd.set_option('display.max_colwidth', None)
query

,nf_numero,nf_item,nf_datahora,nf_timestamp,nf_valor_total,emit_nome,emit_cnpj,emit_bairro,emit_municipio,emit_cep,emit_lat,emit_long,prod_desc,prod_ncm,prod_cfop,prod_quant,prod_unid,prod_valor_unit,prod_valor_total
5373,14890,3,2016-04-28 16:13:44,1461860024,8091.70,medfarmacy hospitalar ltda,10806118000165,mirante,campina grande,58407685,-7.224674,-35.877129,alendronato de sodio 70mg,30049099,5403,216.0,cp,1.20,259.20
7935,15479,17,2016-08-23 14:45:57,1471963557,5902.50,medfarmacy hospitalar ltda,10806118000165,velame,campina grande,58420450,-7.224674,-35.877129,alendronato de sodio 70mg,30049099,5403,200.0,cp,1.20,240.00
9670,15536,2,2016-09-08 11:05:03,1473332703,23043.00,medfarmacy hospitalar ltda,10806118000165,velame,campina grande,58420450,-7.224674,-35.877129,alendronato de sodio 70mg,30049099,5403,400.0,cp,1.78,712.00
10585,14460,4,2016-02-23 16:53:44,1456246424,8230.60,medfarmacy hospitalar ltda,10806118000165,mirante,campina grande,58407685,-7.224674,-35.877129,alendronato de sodio 70mg,30049099,5403,300.0,cp,0.55,165.00
11009,14275,1,2016-01-15 12:44:23,1452861863,3297.10,medfarmacy hospitalar ltda,10806118000165,mirante,campina grande,58407685,-7.224674,-35.877129,alendronato de sodio 70mg,30049099,5403,400.0,cp,0.44,176.00
12119,15543,2,2016-09-09 09:09:46,1473412186,11041.90,medfarmacy hospitalar ltda,10806118000165,velame,campina grande,58420450,-7.224674,-35.877129,alendronato de sodio 70mg,30049099,5403,200.0,cp,1.78,356.00
12777,15190,1,2016-06-22 10:57:17,1466593037,4616.10,medfarmacy hospitalar ltda,10806118000165,mirante,campina grande,58407685,-7.224674,-35.877129,alendronato de sodio 70mg,30049099,5403,400.0,cp,1.67,668.00
13228,14982,5,2016-05-13 11:43:36,1463139816,18760.40,medfarmacy hospitalar ltda,10806118000165,mirante,campina grande,58407685,-7.224674,-35.877129,alendronato de sodio 70mg,30049099,5403,3000.0,cp,0.40,1200.00
17872,14537,2,2016-03-08 11:32:42,1457436762,6265.00,medfarmacy hospitalar ltda,10806118000165,mirante,campina grande,58407685,-7.224674,-35.877129,alendronato de sodio 70mg,30049099,5403,300.0,cp,0.55,165.00
18141,15044,3,2016-05-24 09:47:08,1464083228,9143.92,medfarmacy hospitalar ltda,10806118000165,mirante,campina grande,58407685,-7.224674,-35.877129,alendronato de sodio 70mg,30049099,5403,6000.0,cp,0.40,2400.00
20329,15071,2,2016-05-30 10:14:11,1464603251,3095.57,medfarmacy hospitalar ltda,10806118000165,mirante,campina grande,58407685,-7.224674,-35.877129,alendronato de sodio 70mg,30049099,5403,202.0,cp,1.67,337.34
23072,14902,1,2016-05-02 10:58:59,1462186739,4044.20,medfarmacy hospitalar ltda,10806118000165,mirante,campina grande,58407685,-7.224674,-35.877129,alendronato de sodio 70mg,30049099,5403,400.0,cp,1.67,668.00
23080,15123,1,2016-06-09 08:32:43,1465461163,3961.40,medfarmacy hospitalar ltda,10806118000165,mirante,campina grande,58407685,-7.224674,-35.877129,alendronato de sodio 70mg,30049099,5403,400.0,cp,1.67,668.00
25175,15801,7,2016-12-07 09:45:52,1481103952,6406.70,medfarmacy hospitalar ltda,10806118000165,velame,campina grande,58420450,-7.224674,-35.877129,alendronato de sodio 70mg,30049099,5403,400.0,cp,1.78,712.00
27607,15231,11,2016-07-05 11:07:11,1467716831,9532.50,medfarmacy hospitalar ltda,10806118000165,mirante,campina grande,58407685,-7.224674,-35.877129,alendronato de sodio 70mg,30049099,5403,800.0,cp,1.00,800.00
28260,15515,1,2016-08-29 16:19:40,1472487580,2507.30,medfarmacy hospitalar ltda,10806118000165,velame,campina grande,58420450,-7.224674,-35.877129,alendronato de sodio 70mg,30049099,5403,200.0,cp,1.67,334.00
47711,4699,3,2016-10-28 00:00:00,1477612800,7015.98,dismene distr. de medicamentos do nordeste ltda,16682179000144,centro,timbauba,55870000,-7.511882,-35.316076,alendronato de sodio 70mg c/4,30049099,6403,332.0,cp,1.19,395.08
47720,4843,4,2016-12-02 00:00:00,1480636800,8098.09,dismene distr. de medicamentos do nordeste ltda,16682179000144,centro,timbauba,55870000,-7.511882,-35.316076,alendronato de sodio 70mg c/4,30049099,6403,500.0,cp,1.19,595.00
47948,3861,5,2016-05-14 00:00:00,1463184000,7436.91,dismene distr. de medicamentos do nordeste ltda,16682179000144,centro,timbauba,55870000,-7.511882,-35.316076,"alendronato de sodio 70mg c/4-(imposto ibpt nacional:26,75)",30049099,6403,200.0,cp,1.19,238.00
48376,4519,4,2016-09-22 00:00:00,1474502400,11652.49,dismene distr. de medicamentos do nordeste ltda,16682179000144,centro,timbauba,55870000,-7.511882,-35.316076,alendronato de sodio 70mg c/4 comp,30049099,6403,300.0,cp,1.19,357.00
48647,4286,4,2016-08-15 00:00:00,1471219200,8098.09,dismene distr. de medicamentos do nordeste ltda,16682179000144,centro,timbauba,55870000,-7.511882,-35.316076,alendronato de sodio 70mg c/4,30049099,6403,500.0,cp,1.19,595.00
71403,1990,1,2016-04-11 12:14:00,1460376840,14834.36,kamedica dist de med ltda me,11475796000155,prazeres,jaboatao dos guararapes,54310335,-8.175248,-34.946872,alendronato de sodio 70 mg cx/ 04 comp. (e.m.s),30049099,6108,600.0,cpr,0.92,552.00
71967,127237,2,2016-11-11 14:50:23,1478875823,2028.00,dimaster com de prod hosp ltda,2520829000140,centro,barao de cotegipe,99740000,-27.621469,-52.376532,alendronato de sodio 70mg comprimido delta,30049099,6108,3300.0,cpr,0.36,1188.00
71971,111432,2,2016-02-22 16:37:55,1456159075,192380.00,dimaster com de prod hosp ltda,2520829000140,centro,barao de cotegipe,99740000,-27.621469,-52.376532,alendronato de sodio 70mg comprimido delta,30049099,6108,120000.0,cpr,0.31,37200.00